In [1]:
import json
import pandas as pd
import numpy as np
import random
import pandas.io.sql as psql
from sqlalchemy import create_engine
import sqlalchemy



with open('all_vehicles.json') as fp:
    data = json.load(fp)

data_df = pd.json_normalize(data)

data_2 = data_df.dropna(axis=1, how='all')

data_2 = data_2.drop(columns = ['fueltype1', 'mpgdata', 'charge120'])

#data_df[data_df.columns[::1]].describe()

#data_2.describe()

# data_2 = data_2.rename(columns={'make': 'Make', 
#                                  'model': 'Model', 
#                                  'charge240': 'EV charging 240 Volts', 
#                                  'barrels08': 'Fuel Type Single Fuel #Barrels/Year', 
#                                  'barrelsa08': 'Fuel Type for Dual Fuel(EV, CNG, LPG) #Barrels/Year',
#                                  'city08': 'Single Fuel Type city MPG', 
#                                  'city08u': 'Single Fuel Type City MPG Unrounded', 
#                                  'citya08': 'Dual Fuel Type City MPG', 
#                                  'citya08u': 'Dual Fuel Type City MPG Unrounded',
#                                  'citycd': 'City Gas MPG for Hybrid Vehicles in Charge Depletion Mode', 
#                                  'citye': 'City Electricity Consumption in KW-hrs/100 Miles', 
#                                  'cityuf': 'EPA city Utility Factor(share of Electricity) for PHEV',
#                                  'co2': 'CO2 Emissions from Single Fuel types', 
#                                  'co2a': 'CO2 Emissions from Dual Fuel types', 
#                                  'co2tailpipeagpm': 'CO2 Dual Fuel type tailpipe Grams/mile',                                  
#                                  'co2tailpipegpm': 'CO2 SIngle Fuel type tailpipe Grams/mile',
#                                  'comb08': 'Combined MPG for Single Fuel Types',
#                                  'comb08u': 'Combined MPG for Single Fuel Types Unrounded',
#                                  'comba08': 'Combined MPG for Dual Fuel Types', 
#                                  'comba08u': 'Combined MPG for Dual Fuel Types Unrounded',
#                                  'combe': 'Combined Electricity Consumption in kw-hrs/100 miles',
#                                  'combinedcd': 'Combined MPG for Hybrid Vehicles in Charge Depletion Mode', 
#                                  'combineduf': 'EPA combined Utility Factor(share of Electricity) for PHEV', 
#                                  'cylinders': 'Number of Engine Cylinders', 
#                                  'displ': 'Engine Displacement in Liters', 
#                                  'drive': 'Drive Axel Type', 
#                                  'engid': 'EPA Model Type Index',
#                                  'eng_dscr': 'Type of Engine', 
#                                  'fescore': 'EPA Fuel Score', 
#                                  'fuelcost08': "Annual Fuel cost for Single Fuel Type Vehicles", 
#                                  'fuelcosta08': "Annual Fuel cost for Dual Fuel Type Vehicles", 
#                                  'fueltype': 'Fuel Type for Single and Dual type Vehicles',
#                                  'ghgscore': 'Green House Gas EPA Score', 
#                                  'ghgscorea': 'Green House Gas EPA Score for Dual Fuel Type Vehicles', 
#                                  'highway08': 'Highway MPG for Single Fuel Type Vehicles', 
#                                  'highway08u': 'Highway MPG for Single Fuel Type Vehicles Unrounded',
#                                  'highwaya08': 'Highway MPG for Dual Fuel Type Vehicles', 
#                                  'highwaya08u': 'Highway MPG for Dual Fuel Type Vehicles Unrounded', 
#                                  'highwaycd': 'Highway Gas Consumption in Charge Depletion Mode', 
#                                  'highwaye': 'Highwya Electricity Consumption in kw-hrs/100 Miles', 
#                                  'highwayuf': 'EPA Highway Utility Factor(Share of electricity) for PHEV',
#                                  'hlv': 'Hatchback Luggage Volume by Cubic Feet', 
#                                  'hpv': 'Hatchback Passenger Volume in Cubic Feet', 
#                                  'id': 'Vehicle Record ID', 
#                                  'lv2': '2 Door Luggage Volume in Cubic Feet', 
#                                  'lv4': '4 Door Luggage Volume in Cubic Feet', 
#                                  'phevblended': 'Utilizes Gasoline and Electricity during Charge Depletion Mode', 
#                                  'pv2': '2 Door Passenger Volume in Cubic Feet',
#                                  'pv4': '4 Door Passenger Volume in Cubic Feet', 
#                                  'range': 'EPA range for Fuel Type 1', 
#                                  'rangecity': 'EPA City range for Fuel Type 1', 
#                                  'rangecitya': 'EPA City range for Fuel Type 2', 
#                                  'rangehwy': 'EPA Highway Range for Fuel Type 1', 
#                                  'rangehwya': 'EPA Highway Range for Fuel Type 2',
#                                  'trany': 'Transmission Type', 
#                                  'ucity': 'Unadjusted City MPG for Fuel Type 1', 
#                                  'ucitya': 'Unadjusted City MPG for Fuel Type 2', 
#                                  'uhighway': 'Unadjusted Highway MPG for Fuel Type 1', 
#                                  'uhighwaya': 'Unadjusted Highway MPG for Fuel Type 2', 
#                                  'vclass': 'EPA Vehicle Size Class', 
#                                  'year': 'Year',
#                                  'yousavespend': 'Amount Spent over the next 5 Years compared to Average Vehicle', 
#                                  'guzzler': 'If G or T, Then Subject to Gas Guzzler Tax', 
#                                  'trans_dscr': 'Type of Transmission Used', 
#                                  'tcharger': 'If T, then the Vehicle is TurboCharged', 
#                                  'scharger': 'If S, then the Vehicle is SuperCharged',
#                                  'atvtype': 'Type of Alternative Fuel or Advanced Technology Vehicle', 
#                                  'fueltype2': 'Alternative Fuel Type for Dual Fuel Type Vehicles', 
#                                  'rangea': 'EPA Range for Dual Fuel Type Vehicles', 
#                                  'evmotor': 'Electric Motor', 
#                                  'mfrcode': '3 Character Manufacturers Code', 
#                                  'c240dscr': 'Electric Vehicle Charger Description',
#                                  'charge240b': 'Time to charge an Electric vehicles in hours at 240V for alternate charger', 
#                                  'c240bdscr': 'Electric Vehicle Alternate CHarge Description', 
#                                  'createdon': 'Date that Vehicle Record was Created', 
#                                  'modifiedon': 'Date the Vehicle Record was last Modified', 
#                                  'startstop': 'Vehicle has Start-stop Technology',
#                                  'phevcity': 'EPA Composite Gas/Electric City MPG for Plug-in Hybrid Vehicles', 
#                                  'phevhwy': 'EPA Composite Gas/Electric Highway MPG for Plug-in Hybrid Vehicles', 
#                                  'phevcomb': 'EPa Composite Gas/Electric Combined MPG for Plug-in Hybrid Vehicles', 
#                                  'basemodel': 'Base Model' })

In [7]:
#This randomizes and adds Mock data. Running this will not result in the same results as posted. 


data_mock = pd.DataFrame(data_2)

stock = []
count = 0
reset = random.randint(5, 15)

for i in data_mock['make']:
    if count == reset:
        stock.append(random.randint(1, 9))
        count = 0
        reset = random.randint(5, 15)
    else:
        stock.append(random.randint(0, 3))
    count += 1
data_mock['Stock'] = stock
data_mock.head()

vin = []
makes = []
models = []


for i, j, s, d in zip(data_mock['make'], data_mock['model'], data_mock['Stock'], data_mock['id']):
    make = i[0]
    model = j[0]
    make1 = i
    model1 = j
    num = s
    car_id = d
    for row in range(num):
        number = np.random.randint(1111, 9999)
        cond = np.random.choice(['Used', 'New'])
        vin_num = f'{make}{model}{number}'
        
        if cond == 'Used':
            mileage = np.random.randint(501, 150000)
        elif cond == 'New':
            mileage = np.random.randint(0, 500)

        
        vin.append([vin_num, make1, model1, cond, mileage, num, car_id])

        
    

vin = pd.DataFrame(vin, columns=['VIN', 'make', 'model', 'Condition', 'Mileage', 'Stock', 'id'])
vin.head()

      VIN       make           model Condition  Mileage  Stock     id
0  FB8194       Ford      Bronco 4WD       New      392      2   2818
1  FB4490       Ford      Bronco 4WD      Used    67258      2   2818
2  FL9844       Ford       LTD Wagon       New      435      1  28191
3  CS9807  Chevrolet  S10 Pickup 2WD      Used    27965      2  28226
4  CS4122  Chevrolet  S10 Pickup 2WD      Used    73184      2  28226

In [8]:
vin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88331 entries, 0 to 88330
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   VIN        88331 non-null  object
 1   make       88331 non-null  object
 2   model      88331 non-null  object
 3   Condition  88331 non-null  object
 4   Mileage    88331 non-null  int64
 5   Stock      88331 non-null  int64
 6   id         88331 non-null  object
dtypes: int64(2), object(5)
memory usage: 4.7+ MB

In [9]:
data_clean = pd.merge(vin, data_mock, how='inner', on= ['make', 'model', 'id', 'Stock'])
#data_clean.drop('Make_y', axis=1, inplace=True)
#data_clean = data_clean.rename(columns={'Make_x': 'Make'})
#data_final = data_clean.drop_duplicates(subset='VIN', keep= 'first')

In [10]:
data_clean.head(20)

,VIN,make,model,Condition,Mileage,Stock,id,barrels08,barrelsa08,charge240,...,c240dscr,charge240b,c240bdscr,createdon,modifiedon,startstop,phevcity,phevhwy,phevcomb,basemodel
0,FB8194,Ford,Bronco 4WD,New,392,2,2818,22.885385,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Bronco
1,FB4490,Ford,Bronco 4WD,Used,67258,2,2818,22.885385,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Bronco
2,FL9844,Ford,LTD Wagon,New,435,1,28191,15.658421,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,LTD
3,CS9807,Chevrolet,S10 Pickup 2WD,Used,27965,2,28226,12.935217,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,S10 Pickup
4,CS4122,Chevrolet,S10 Pickup 2WD,Used,73184,2,28226,12.935217,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,S10 Pickup
5,MT3117,Mitsubishi,Truck 2WD,New,475,2,28265,12.935217,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Truck
6,MT5833,Mitsubishi,Truck 2WD,Used,18575,2,28265,12.935217,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Truck
7,FR9545,Ford,Ranger Pickup 4WD,Used,85426,2,28277,16.528333,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Ranger
8,FR7439,Ford,Ranger Pickup 4WD,New,465,2,28277,16.528333,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Ranger
9,GT3341,GMC,T15 (S15) Jimmy 4WD,New,91,3,2831,18.594375,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Jimmy
10,GT6713,GMC,T15 (S15) Jimmy 4WD,Used,145770,3,2831,18.594375,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Jimmy
11,GT2187,GMC,T15 (S15) Jimmy 4WD,New,103,3,2831,18.594375,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Jimmy
12,JJ1893,Jeep,J-10 Pickup 4WD,New,184,1,28370,18.594375,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,J-10 Pickup
13,GV9627,GMC,Vandura G15/25 2WD,Used,140497,3,28400,18.799737,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Vandura
14,GV5100,GMC,Vandura G15/25 2WD,New,69,3,28400,18.799737,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Vandura
15,GV9056,GMC,Vandura G15/25 2WD,New,438,3,28400,18.799737,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Vandura
16,FE7842,Ford,E150 Club Wagon 2WD,Used,67440,3,28415,24.792500,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,E150 Club Wagon
17,FE8036,Ford,E150 Club Wagon 2WD,New,116,3,28415,24.792500,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,E150 Club Wagon
18,FE1263,Ford,E150 Club Wagon 2WD,New,379,3,28415,24.792500,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,E150 Club Wagon
19,GG7492,GMC,G15/25 Rally 2WD,New,452,2,28419,18.799737,0.0,0.0,...,None,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Rally

In [16]:
data_clean = data_clean.fillna(0)
#data_clean['EPA Fuel Score']
data_clean = pd.DataFrame(data_clean)
data_clean = data_clean.convert_dtypes()

In [23]:
#data_clean.to_csv('out.csv', index=False)

column = data_clean.columns
data_val = data_clean.dtypes

column = pd.DataFrame(column)

# postgres = [column, data_val]
# postgres = pd.DataFrame(postgres)
# postgres.to_csv('columns.csv', index=False)

In [28]:
engine = sqlalchemy.create_engine('sqlite:///Inventory.db')
column.to_sql('Inventory', engine, if_exists='replace', index=True)

85