In [2]:
import json
import pandas as pd
import numpy as np
import random


with open('all_vehicles.json') as fp:
    data = json.load(fp)

data_df = pd.json_normalize(data)

data_2 = data_df.dropna(axis=1, how='all')

data_2 = data_2.drop(columns = ['fueltype1', 'mpgdata', 'charge120'])

#data_df[data_df.columns[::1]].describe()

#data_2.describe()

# data_2 = data_2.rename(columns={'make': 'Make', 
#                                  'model': 'Model', 
#                                  'charge240': 'EV charging 240 Volts', 
#                                  'barrels08': 'Fuel Type Single Fuel #Barrels/Year', 
#                                  'barrelsa08': 'Fuel Type for Dual Fuel(EV, CNG, LPG) #Barrels/Year',
#                                  'city08': 'Single Fuel Type city MPG', 
#                                  'city08u': 'Single Fuel Type City MPG Unrounded', 
#                                  'citya08': 'Dual Fuel Type City MPG', 
#                                  'citya08u': 'Dual Fuel Type City MPG Unrounded',
#                                  'citycd': 'City Gas MPG for Hybrid Vehicles in Charge Depletion Mode', 
#                                  'citye': 'City Electricity Consumption in KW-hrs/100 Miles', 
#                                  'cityuf': 'EPA city Utility Factor(share of Electricity) for PHEV',
#                                  'co2': 'CO2 Emissions from Single Fuel types', 
#                                  'co2a': 'CO2 Emissions from Dual Fuel types', 
#                                  'co2tailpipeagpm': 'CO2 Dual Fuel type tailpipe Grams/mile',                                  
#                                  'co2tailpipegpm': 'CO2 SIngle Fuel type tailpipe Grams/mile',
#                                  'comb08': 'Combined MPG for Single Fuel Types',
#                                  'comb08u': 'Combined MPG for Single Fuel Types Unrounded',
#                                  'comba08': 'Combined MPG for Dual Fuel Types', 
#                                  'comba08u': 'Combined MPG for Dual Fuel Types Unrounded',
#                                  'combe': 'Combined Electricity Consumption in kw-hrs/100 miles',
#                                  'combinedcd': 'Combined MPG for Hybrid Vehicles in Charge Depletion Mode', 
#                                  'combineduf': 'EPA combined Utility Factor(share of Electricity) for PHEV', 
#                                  'cylinders': 'Number of Engine Cylinders', 
#                                  'displ': 'Engine Displacement in Liters', 
#                                  'drive': 'Drive Axel Type', 
#                                  'engid': 'EPA Model Type Index',
#                                  'eng_dscr': 'Type of Engine', 
#                                  'fescore': 'EPA Fuel Score', 
#                                  'fuelcost08': "Annual Fuel cost for Single Fuel Type Vehicles", 
#                                  'fuelcosta08': "Annual Fuel cost for Dual Fuel Type Vehicles", 
#                                  'fueltype': 'Fuel Type for Single and Dual type Vehicles',
#                                  'ghgscore': 'Green House Gas EPA Score', 
#                                  'ghgscorea': 'Green House Gas EPA Score for Dual Fuel Type Vehicles', 
#                                  'highway08': 'Highway MPG for Single Fuel Type Vehicles', 
#                                  'highway08u': 'Highway MPG for Single Fuel Type Vehicles Unrounded',
#                                  'highwaya08': 'Highway MPG for Dual Fuel Type Vehicles', 
#                                  'highwaya08u': 'Highway MPG for Dual Fuel Type Vehicles Unrounded', 
#                                  'highwaycd': 'Highway Gas Consumption in Charge Depletion Mode', 
#                                  'highwaye': 'Highwya Electricity Consumption in kw-hrs/100 Miles', 
#                                  'highwayuf': 'EPA Highway Utility Factor(Share of electricity) for PHEV',
#                                  'hlv': 'Hatchback Luggage Volume by Cubic Feet', 
#                                  'hpv': 'Hatchback Passenger Volume in Cubic Feet', 
#                                  'id': 'Vehicle Record ID', 
#                                  'lv2': '2 Door Luggage Volume in Cubic Feet', 
#                                  'lv4': '4 Door Luggage Volume in Cubic Feet', 
#                                  'phevblended': 'Utilizes Gasoline and Electricity during Charge Depletion Mode', 
#                                  'pv2': '2 Door Passenger Volume in Cubic Feet',
#                                  'pv4': '4 Door Passenger Volume in Cubic Feet', 
#                                  'range': 'EPA range for Fuel Type 1', 
#                                  'rangecity': 'EPA City range for Fuel Type 1', 
#                                  'rangecitya': 'EPA City range for Fuel Type 2', 
#                                  'rangehwy': 'EPA Highway Range for Fuel Type 1', 
#                                  'rangehwya': 'EPA Highway Range for Fuel Type 2',
#                                  'trany': 'Transmission Type', 
#                                  'ucity': 'Unadjusted City MPG for Fuel Type 1', 
#                                  'ucitya': 'Unadjusted City MPG for Fuel Type 2', 
#                                  'uhighway': 'Unadjusted Highway MPG for Fuel Type 1', 
#                                  'uhighwaya': 'Unadjusted Highway MPG for Fuel Type 2', 
#                                  'vclass': 'EPA Vehicle Size Class', 
#                                  'year': 'Year',
#                                  'yousavespend': 'Amount Spent over the next 5 Years compared to Average Vehicle', 
#                                  'guzzler': 'If G or T, Then Subject to Gas Guzzler Tax', 
#                                  'trans_dscr': 'Type of Transmission Used', 
#                                  'tcharger': 'If T, then the Vehicle is TurboCharged', 
#                                  'scharger': 'If S, then the Vehicle is SuperCharged',
#                                  'atvtype': 'Type of Alternative Fuel or Advanced Technology Vehicle', 
#                                  'fueltype2': 'Alternative Fuel Type for Dual Fuel Type Vehicles', 
#                                  'rangea': 'EPA Range for Dual Fuel Type Vehicles', 
#                                  'evmotor': 'Electric Motor', 
#                                  'mfrcode': '3 Character Manufacturers Code', 
#                                  'c240dscr': 'Electric Vehicle Charger Description',
#                                  'charge240b': 'Time to charge an Electric vehicles in hours at 240V for alternate charger', 
#                                  'c240bdscr': 'Electric Vehicle Alternate CHarge Description', 
#                                  'createdon': 'Date that Vehicle Record was Created', 
#                                  'modifiedon': 'Date the Vehicle Record was last Modified', 
#                                  'startstop': 'Vehicle has Start-stop Technology',
#                                  'phevcity': 'EPA Composite Gas/Electric City MPG for Plug-in Hybrid Vehicles', 
#                                  'phevhwy': 'EPA Composite Gas/Electric Highway MPG for Plug-in Hybrid Vehicles', 
#                                  'phevcomb': 'EPa Composite Gas/Electric Combined MPG for Plug-in Hybrid Vehicles', 
#                                  'basemodel': 'Base Model' })

#data_2.columns
#data_2.head()
#data_2[['Make', 'Model', 'year']]
# test = data_2.loc[data_2['Year'] == '1986']
# test = test.loc[test['Model'] == 'Bronco 4WD']
# test[['Model', 'Base Model', 'Year']]

In [24]:
data_mock = pd.DataFrame(data_2)

stock = []
count = 0
reset = random.randint(5, 15)

for i in data_mock['make']:
    if count == reset:
        stock.append(random.randint(1, 9))
        count = 0
        reset = random.randint(5, 15)
    else:
        stock.append(random.randint(0, 3))
    count += 1
data_mock['Stock'] = stock
data_mock.head()

vin = []
makes = []
models = []


for i, j, s, h in zip(data_mock['make'], data_mock['model'], data_mock['Stock'], data_mock['id']):
    make = i[0]
    model = j[0]
    make1 = i
    model1 = j
    num = s
    id = h
    for row in range(num):
        number = np.random.randint(100001, 999999)
        cond = np.random.choice(['Used', 'New'])
        vin_num = f'{make}{model}{number}'
        
        if cond == 'Used':
            mileage = np.random.randint(501, 150000)
        elif cond == 'New':
            mileage = np.random.randint(0, 500)

        
        vin.append([vin_num, make1, model1, cond, mileage, id])

        
    

vin = pd.DataFrame(vin, columns=['VIN', 'make', 'model', 'Condition', 'Mileage', 'id'])
vin.head()

        VIN  make       model Condition  Mileage     id
0  FB798149  Ford  Bronco 4WD      Used    76625   2818
1  FB197163  Ford  Bronco 4WD      Used   109159   2818
2  FB156983  Ford  Bronco 4WD       New      294   2818
3  FL234453  Ford   LTD Wagon      Used    17229  28191
4  FL187365  Ford   LTD Wagon       New      323  28191

In [25]:
vin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88296 entries, 0 to 88295
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   VIN        88296 non-null  object
 1   make       88296 non-null  object
 2   model      88296 non-null  object
 3   Condition  88296 non-null  object
 4   Mileage    88296 non-null  int64
 5   id         88296 non-null  object
dtypes: int64(1), object(5)
memory usage: 4.0+ MB

In [35]:
data_clean = pd.merge(vin, data_mock, how='right', on= ('id', 'make', 'model'))
data_clean.dropna(subset=['VIN'], inplace=True)
data_clean.drop_duplicates(subset='VIN', keep='first', inplace=True)
data_clean = data_clean.rename(columns={'Make_x': 'Make'})
data_clean.to_csv('out.csv', index=False)

In [34]:
data_clean.head(30)

,VIN,make,model,Condition,Mileage,id,barrels08,barrelsa08,charge240,city08,...,charge240b,c240bdscr,createdon,modifiedon,startstop,phevcity,phevhwy,phevcomb,basemodel,Stock
0,FB798149,Ford,Bronco 4WD,Used,76625.0,2818,22.885385,0.0,0.0,12,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Bronco,3
1,FB197163,Ford,Bronco 4WD,Used,109159.0,2818,22.885385,0.0,0.0,12,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Bronco,3
2,FB156983,Ford,Bronco 4WD,New,294.0,2818,22.885385,0.0,0.0,12,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Bronco,3
3,FL234453,Ford,LTD Wagon,Used,17229.0,28191,15.658421,0.0,0.0,17,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,LTD,2
4,FL187365,Ford,LTD Wagon,New,323.0,28191,15.658421,0.0,0.0,17,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,LTD,2
5,CS325974,Chevrolet,S10 Pickup 2WD,Used,18360.0,28226,12.935217,0.0,0.0,21,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,S10 Pickup,2
6,CS710403,Chevrolet,S10 Pickup 2WD,Used,98726.0,28226,12.935217,0.0,0.0,21,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,S10 Pickup,2
7,DR987056,Dodge,Ram 50 Pickup 2WD,New,225.0,28243,14.875500,0.0,0.0,18,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Ram 50 Pickup,1
8,FR237962,Ford,Ranger Pickup 2WD,Used,61963.0,28244,15.658421,0.0,0.0,18,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Ranger,2
9,FR765058,Ford,Ranger Pickup 2WD,Used,13321.0,28244,15.658421,0.0,0.0,18,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Ranger,2
10,MT610735,Mitsubishi,Truck 2WD,New,35.0,28265,12.935217,0.0,0.0,21,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Truck,1
11,FR733313,Ford,Ranger Pickup 4WD,Used,91744.0,28277,16.528333,0.0,0.0,17,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Ranger,2
12,FR737127,Ford,Ranger Pickup 4WD,Used,10021.0,28277,16.528333,0.0,0.0,17,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Ranger,2
13,GT495976,GMC,T15 (S15) Jimmy 4WD,Used,34955.0,2831,18.594375,0.0,0.0,14,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Jimmy,2
14,GT145082,GMC,T15 (S15) Jimmy 4WD,Used,104617.0,2831,18.594375,0.0,0.0,14,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Jimmy,2
15,JJ101273,Jeep,J-10 Pickup 4WD,Used,100066.0,28370,18.594375,0.0,0.0,15,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,J-10 Pickup,1
16,GV685153,GMC,Vandura G15/25 2WD,Used,109851.0,28400,18.799737,0.0,0.0,18,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Vandura,2
17,GV359645,GMC,Vandura G15/25 2WD,New,346.0,28400,18.799737,0.0,0.0,18,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Vandura,2
19,GG556270,GMC,G15/25 Rally 2WD,New,401.0,28419,18.799737,0.0,0.0,18,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Rally,2
20,GG747487,GMC,G15/25 Rally 2WD,New,343.0,28419,18.799737,0.0,0.0,18,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Rally,2
21,TV252073,Toyota,Van 2WD,Used,21692.0,28422,14.167143,0.0,0.0,20,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Van,2
22,TV381216,Toyota,Van 2WD,New,194.0,28422,14.167143,0.0,0.0,20,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Van,2
23,VV619427,Volkswagen,Vanagon 2WD,Used,136661.0,28424,18.594375,0.0,0.0,15,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Vanagon,3
24,VV503609,Volkswagen,Vanagon 2WD,Used,136095.0,28424,18.594375,0.0,0.0,15,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Vanagon,3
25,VV871596,Volkswagen,Vanagon 2WD,Used,137323.0,28424,18.594375,0.0,0.0,15,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Vanagon,3
27,DC268497,Dodge,Caravan/Ram Van 2WD,Used,125839.0,28439,14.167143,0.0,0.0,18,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Caravan/Ram Van,2
28,DC661972,Dodge,Caravan/Ram Van 2WD,Used,115527.0,28439,14.167143,0.0,0.0,18,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Caravan/Ram Van,2
29,JC624673,Jeep,Cherokee/Wagoneer 4WD,New,82.0,28490,14.167143,0.0,0.0,19,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Cherokee/Wagoneer,2
30,JC387677,Jeep,Cherokee/Wagoneer 4WD,Used,130214.0,28490,14.167143,0.0,0.0,19,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,Cherokee/Wagoneer,2
31,JC540575,Jeep,CJ7 4WD,Used,97036.0,28494,14.167143,0.0,0.0,19,...,0.0,None,2013-01-01,2013-01-01,None,0,0,0,CJ,1

         Make       Model  Year  Stock
0        Ford  Bronco 4WD  1986      8
1        Ford  Bronco 4WD  1986      8
2        Ford  Bronco 4WD  1986      8
3        Ford  Bronco 4WD  1986      8
4        Ford  Bronco 4WD  1986      8
...       ...         ...   ...    ...
8232970  Ford  Bronco 4WD  1986      9
8232971  Ford  Bronco 4WD  1986      9
8232972  Ford  Bronco 4WD  1986      9
8232973  Ford  Bronco 4WD  1986      9
8232974  Ford  Bronco 4WD  1986      9

[3132 rows x 4 columns]